server:
    port: 8080

spring:
    application:
        name: customer
    jpa:
        defer-datasource-initialization: true
    datasource:
        username: 'abbas'
        url: jdbc:postgresql://localhost:5432/customer
        password: 'password'
        jpa:
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.PostgreSQL10Dialect
                    format_sql: 'true'
            hibernate:
                    ddl-auto: 'create'
            show-sql: 'true'