server:
    port: 8081

spring:
    application:
        name: fraud
    datasource:
        username: 'abbas'
        url: jdbc:postgresql://localhost:5432/fraud
        password: 'password'
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                format_sql: 'true'
        hibernate:
            ddl-auto: 'update'
        show-sql: 'true'